spring:
 jpa:
    show-sql: true
 profiles:
    # 外置jdbc和log配置文件
    active: jdbc,log,redis,mail
 thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
#单独放到外置配置文件中
#  datasource:
#     url: jdbc:mysql://127.0.0.1:3306/advert?useUnicode=true&characterEncoding=utf8
#     username: root
#     password: root
#     driver-class-name: com.mysql.jdbc.Driver
#     initial-size: 10
#     max-active: 100
#     min-idle: 10
#     max-wait: 60000
mybatis:
  type-aliases-package: com.sdt.advert.dao
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /
#logging:
#  config: classpath:logback-spring_backup.xml
logging:
  level:
    com:
      sdt:
        advert: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
